version: "3"
services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"